@extends('layouts.front')

@section('content')
<section class="relative isolate overflow-hidden bg-gray-950 text-white"><div class="pointer-events-none absolute inset-0 -z-20 bg-linear-to-br from-gray-950 via-brand-950 to-gray-900" aria-hidden="true"></div><div class="hero-energy-grid pointer-events-none absolute inset-0 -z-10 opacity-20" aria-hidden="true"></div><div class="mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-5 px-4 py-9 sm:px-8 sm:py-12 lg:px-10"><div><p class="text-theme-xs font-semibold uppercase tracking-[0.2em] text-warning-300">{{ __('Owner workspace') }} <span class="mx-1 text-gray-500">/</span> {{ __('Catalog') }}</p><h1 class="mt-3 text-title-sm font-semibold tracking-tight sm:text-title-md">{{ __('My equipment') }}</h1><p class="mt-2 max-w-2xl text-theme-sm text-gray-300">{{ __('Manage your listings and keep their energy details accurate.') }}</p></div><a href="{{ route('front.my-publish') }}" class="button-base button-primary min-h-11 px-4 text-theme-sm"><span aria-hidden="true">＋</span> {{ __('Publish equipment') }}</a></div></section>
@include('pages.front.partials.owner-nav')
<main class="mx-auto w-full max-w-7xl space-y-7 px-4 py-7 sm:px-8 sm:py-10 lg:px-10"><nav aria-label="{{ __('Breadcrumb') }}" class="flex items-center gap-2 text-theme-xs text-gray-500"><a href="{{ route('front.owner-dashboard') }}" class="hover:text-brand-700">{{ __('Owner workspace') }}</a><span aria-hidden="true">/</span><span aria-current="page" class="font-medium text-gray-800 dark:text-gray-200">{{ __('My equipment') }}</span></nav>
    @if(session('status'))<p role="status" aria-live="polite" class="rounded-2xl border border-success-200 bg-success-50 px-4 py-3 text-theme-sm text-success-700 dark:border-success-500/30 dark:bg-success-500/10 dark:text-success-300">{{ session('status') }}</p>@endif
    <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:p-7"><div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ __('Your listings') }}</h2><p class="mt-1 text-theme-xs text-gray-500 dark:text-gray-400">{{ trans_choice(':count listing|:count listings', $equipment->total(), ['count' => $equipment->total()]) }}</p></div><a href="{{ route('front.my-publish') }}" class="button-base button-primary min-h-10 px-4 text-theme-xs">{{ __('Add equipment') }} <span aria-hidden="true">＋</span></a></div>
        @if($equipment->isEmpty())<div class="rounded-xl border border-dashed border-gray-300 p-10 text-center dark:border-gray-700"><h2 class="font-semibold text-gray-900 dark:text-white">{{ __('No equipment yet') }}</h2><p class="mt-2 text-theme-sm text-gray-500">{{ __('Publish your first solar panel, battery or wind turbine.') }}</p><a href="{{ route('front.my-publish') }}" class="button-base button-primary mt-5 inline-flex px-4 py-2.5 text-theme-sm">{{ __('Publish equipment') }}</a></div>@else
        <div class="overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-800"><table class="w-full min-w-[900px] text-start text-theme-xs"><thead class="bg-gray-50 text-gray-500 dark:bg-white/5 dark:text-gray-400"><tr><th class="px-4 py-3 text-start font-medium">{{ __('Equipment') }}</th><th class="px-4 py-3 text-start font-medium">{{ __('Category') }}</th><th class="px-4 py-3 text-start font-medium">{{ __('Energy') }}</th><th class="px-4 py-3 text-start font-medium">{{ __('Price / day') }}</th><th class="px-4 py-3 text-start font-medium">{{ __('Publication') }}</th><th class="px-4 py-3 text-start font-medium">{{ __('Availability') }}</th><th class="px-4 py-3 text-end font-medium">{{ __('Actions') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@foreach($equipment as $item)<tr><td class="px-4 py-4"><a href="{{ route('front.my-equipment-detail', $item) }}" class="font-semibold text-gray-900 hover:text-brand-700 dark:text-white dark:hover:text-brand-300">{{ $item->name }}</a><span class="mt-1 block text-[11px] text-gray-500">{{ $item->brand }} {{ $item->model }} · {{ $item->location }}</span></td><td class="px-4 py-4 text-gray-700 dark:text-gray-300">{{ $item->category->name }}</td><td class="px-4 py-4 text-gray-700 dark:text-gray-300">{{ $item->energyProfile?->power_watts ?? '—' }} W<br>{{ $item->energyProfile?->capacity_wh ?? '—' }} Wh</td><td class="px-4 py-4 font-medium text-gray-900 dark:text-white">{{ number_format((float) $item->price_per_day, 2) }} TND</td><td class="px-4 py-4"><span class="rounded-full bg-warning-50 px-2.5 py-1 text-[11px] font-semibold text-warning-800 dark:bg-warning-500/15 dark:text-warning-300">{{ __(str_replace('_', ' ', ucfirst($item->approval_status))) }}</span></td><td class="px-4 py-4"><span class="rounded-full bg-brand-50 px-2.5 py-1 text-[11px] font-semibold text-brand-800 dark:bg-brand-500/15 dark:text-brand-300">{{ __(ucfirst($item->status)) }}</span></td><td class="px-4 py-4 text-end"><a href="{{ route('front.my-equipment-edit', $item) }}" class="rounded-lg px-3 py-2 font-semibold text-brand-700 hover:bg-brand-50 dark:text-brand-300 dark:hover:bg-brand-500/10">{{ __('Edit') }}</a><a href="{{ route('front.my-equipment-detail', $item) }}" class="ms-1 rounded-lg px-3 py-2 text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:text-white">{{ __('Details') }}</a><form class="ms-1 inline" method="POST" action="{{ route('front.my-equipment.destroy', $item) }}">@csrf @method('DELETE')<button type="submit" onclick="return confirm(@js(__('Delete this listing?')))" class="rounded-lg px-3 py-2 text-error-700 hover:bg-error-50 dark:text-error-300 dark:hover:bg-error-500/10">{{ __('Delete') }}</button></form></td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $equipment->links() }}</div>@endif
    </section>
</main>
@endsection
