<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create the "rentals" table.
     * A rental is a reservation that has become an actual loan of an equipment.
     */
    public function up(): void
    {
        Schema::create('rentals', function (Blueprint $table) {
            $table->id();

            // Unique human readable code, e.g. "RNT-2026-0001" (generated by the app)
            $table->string('reference')->unique();

            // TODO: once Student 1's "equipment" table is merged, add the real
            // foreign key in a new migration:
            //   $table->foreign('equipment_id')->references('id')->on('equipment');
            // Until then it is a simple indexed column so our migration never fails.
            $table->unsignedBigInteger('equipment_id')->index();

            // The renter. "users" already exists, so we can use a real foreign key.
            // cascadeOnDelete: if the user is deleted, his rentals are deleted too.
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();

            // TODO: same as equipment_id, add the foreign key to Student 4's
            // "reservations" table once it is merged.
            // Nullable: a rental can exist before the reservation module is ready.
            // Unique: one reservation can become only one rental (1-1 link).
            $table->unsignedBigInteger('reservation_id')->nullable()->unique();

            $table->date('start_date');
            $table->date('end_date');

            // Money amount with 2 decimals (up to 99 999 999.99)
            $table->decimal('total_amount', 10, 2);

            // Value comes from App\Enums\RentalStatus
            $table->string('status')->default('pending')->index();

            $table->timestamps(); // created_at and updated_at
        });
    }

    /**
     * Undo the migration (used by "php artisan migrate:rollback").
     */
    public function down(): void
    {
        Schema::dropIfExists('rentals');
    }
};
