@extends('layouts.front')

@php
    $steps = [__('Reservation'), __('Summary'), __('Payment'), __('Confirmation')];
    $activeStep = match ($slug) {
        'reserve' => 0,
        'booking-summary' => 1,
        'payment' => 2,
        default => 3,
    };
@endphp

@section('content')
    <section class="relative isolate overflow-hidden bg-gray-950 text-white">
        <div class="pointer-events-none absolute inset-0 -z-20 bg-linear-to-br from-gray-950 via-brand-950 to-gray-900" aria-hidden="true"></div>
        <div class="hero-energy-grid pointer-events-none absolute inset-0 -z-10 opacity-20" aria-hidden="true"></div>
        <div class="mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-5 px-4 py-9 sm:px-8 sm:py-12 lg:px-10">
            <div><p class="text-theme-xs font-semibold uppercase tracking-[0.2em] text-warning-300">{{ __('Secure booking preview') }}</p><h1 class="mt-3 text-title-sm font-semibold tracking-tight sm:text-title-md">{{ __($title) }}</h1><p class="mt-2 max-w-2xl text-theme-sm text-gray-300">{{ __('A guided reservation journey for :equipment.', ['equipment' => $item->name]) }}</p></div>
            <a href="{{ route('front.equipment.show', $item->id) }}" class="inline-flex min-h-10 items-center rounded-lg border border-white/20 px-4 text-theme-xs font-semibold text-white hover:bg-white/10">{{ __('Back to equipment') }}</a>
        </div>
    </section>

    <main class="mx-auto w-full max-w-5xl space-y-7 px-4 py-8 sm:px-8 sm:py-10">
        <ol aria-label="{{ __('Booking progress') }}" class="grid grid-cols-2 gap-3 sm:grid-cols-4">
            @foreach ($steps as $index => $label)
                <li class="flex items-center gap-3 rounded-xl border p-3 {{ $index <= $activeStep ? 'border-brand-200 bg-brand-50 dark:border-brand-500/30 dark:bg-brand-500/10' : 'border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]' }}">
                    <span class="flex size-8 shrink-0 items-center justify-center rounded-full text-theme-xs font-semibold {{ $index < $activeStep ? 'bg-success-600 text-white' : ($index === $activeStep ? 'bg-brand-700 text-white dark:bg-brand-500' : 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400') }}">{{ $index < $activeStep ? '✓' : $index + 1 }}</span>
                    <span class="text-theme-xs font-semibold {{ $index === $activeStep ? 'text-brand-900 dark:text-brand-200' : 'text-gray-600 dark:text-gray-400' }}">{{ $label }}</span>
                </li>
            @endforeach
        </ol>
        <div class="flex items-start gap-3 rounded-2xl border border-warning-200 bg-warning-50 px-4 py-3.5 text-theme-xs leading-5 text-warning-900 dark:border-warning-500/30 dark:bg-warning-500/10 dark:text-warning-200" role="status"><span aria-hidden="true">✳</span><p><span class="font-semibold">{{ __('Simulation only.') }}</span> {{ __('Availability, reservations, invoices and payments are not connected to a backend.') }}</p></div>

        @if ($slug === 'reserve')
            <div class="grid items-start gap-6 lg:grid-cols-[1fr_21rem]" x-data="{ start: '', end: '', price: {{ (float) $item->price_per_day }}, get days() { if (!this.start || !this.end) return 0; return Math.max(0, Math.floor((new Date(this.end) - new Date(this.start)) / 86400000) + 1) }, get overlaps() { if ({{ $item->id }} !== 1 || !this.start || !this.end) return false; return this.start <= '2026-10-11' && this.end >= '2026-10-09' }, get subtotal() { return this.days * this.price }, get tax() { return this.subtotal * 0.19 }, get total() { return this.subtotal + this.tax } }">
                <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:p-7">
                    <h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ __('Choose your dates') }}</h2><p class="mt-1 text-theme-xs text-gray-500 dark:text-gray-400">{{ __('Select a pickup and return date to see your estimated total.') }}</p>
                    <div class="mt-6 grid gap-4 sm:grid-cols-2">
                        <label for="booking-start" class="block text-theme-xs font-medium text-gray-700 dark:text-gray-300">{{ __('Start date') }}<input id="booking-start" type="date" name="start" min="2026-10-04" x-model="start" required class="mt-1.5 min-h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-theme-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"></label>
                        <label for="booking-end" class="block text-theme-xs font-medium text-gray-700 dark:text-gray-300">{{ __('End date') }}<input id="booking-end" type="date" name="end" min="2026-10-04" x-model="end" :min="start || '2026-10-04'" required class="mt-1.5 min-h-11 w-full rounded-lg border border-gray-300 bg-white px-3 text-theme-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white"></label>
                    </div>
                    <div x-show="overlaps" x-cloak role="alert" class="mt-5 rounded-xl border border-error-200 bg-error-50 px-4 py-3 text-theme-xs text-error-800 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-200"><span class="font-semibold">{{ __('Sample date conflict.') }}</span> {{ __('This example listing is marked unavailable from 9–11 Oct. Choose other dates. The real overlap check must be enforced on the server.') }}</div>
                    <div class="mt-5 rounded-xl bg-brand-50 p-4 dark:bg-brand-500/10" aria-live="polite"><div class="flex items-center justify-between text-theme-xs text-gray-600 dark:text-gray-300"><span x-text="days + ' {{ __('day(s)') }} × {{ number_format($item->price_per_day, 2) }} TND'"></span><span class="font-semibold text-gray-900 dark:text-white"><span x-text="subtotal.toFixed(2)"></span> TND</span></div><div class="mt-3 flex items-center justify-between text-theme-xs text-gray-600 dark:text-gray-300"><span>{{ __('Tax · 19%') }}</span><span><span x-text="tax.toFixed(2)"></span> TND</span></div><div class="mt-3 flex items-center justify-between border-t border-brand-200 pt-3 text-theme-sm font-semibold text-brand-900 dark:border-brand-500/30 dark:text-brand-100"><span>{{ __('Estimated total') }}</span><span><span x-text="total.toFixed(2)"></span> TND</span></div></div>
                    <form method="GET" action="{{ route('front.booking-summary', ['equipment' => $item->id]) }}" class="mt-5"><input type="hidden" name="start" :value="start"><input type="hidden" name="end" :value="end"><button type="submit" :disabled="!start || !end || days < 1 || overlaps" class="button-base button-primary min-h-12 w-full px-4 text-theme-sm disabled:cursor-not-allowed disabled:opacity-50">{{ __('Review reservation') }} <span aria-hidden="true">→</span></button></form>
                </section>
                <aside class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><img src="{{ asset($item->image) }}" alt="{{ $item->name }}" class="aspect-16/10 w-full bg-brand-50 object-cover"><div class="p-5"><p class="text-theme-xs font-semibold uppercase tracking-wider text-brand-700 dark:text-brand-300">{{ __($item->category->name) }}</p><h2 class="mt-2 font-semibold text-gray-900 dark:text-white">{{ $item->name }}</h2><p class="mt-2 text-theme-xs text-gray-500 dark:text-gray-400">{{ __('Shared by :owner · :location', ['owner' => $item->owner, 'location' => $item->location]) }}</p><p class="mt-4 text-theme-sm font-semibold text-gray-900 dark:text-white">{{ number_format($item->price_per_day, 2) }} TND <span class="font-normal text-gray-500">/ {{ __('day') }}</span></p></div></aside>
            </div>
        @elseif ($slug === 'booking-summary')
            <section class="grid items-start gap-6 lg:grid-cols-[1fr_21rem]" x-data="{ start: @js($startDate), end: @js($endDate), price: {{ (float) $item->price_per_day }}, get days() { if (!this.start || !this.end) return 0; return Math.max(0, Math.floor((new Date(this.end) - new Date(this.start)) / 86400000) + 1) }, get subtotal() { return this.days * this.price }, get tax() { return this.subtotal * 0.19 }, get total() { return this.subtotal + this.tax } }">
                <article class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:p-7"><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ __('Review before you continue') }}</h2><p class="mt-1 text-theme-xs text-gray-500">{{ __('Confirm the details and read the sample rental terms.') }}</p><dl class="mt-6 grid gap-4 sm:grid-cols-2">@foreach ([[__('Equipment'), $item->name], [__('Owner'), $item->owner], [__('Start date'), $startDate ?: __('Not selected')], [__('End date'), $endDate ?: __('Not selected')], [__('Pickup location'), $item->location], [__('Condition'), $item->condition]] as [$label, $value])<div class="rounded-xl bg-gray-50 p-4 dark:bg-white/5"><dt class="text-theme-xs text-gray-500">{{ $label }}</dt><dd class="mt-1 font-semibold text-gray-900 dark:text-white">{{ $value }}</dd></div>@endforeach</dl><div class="mt-6 rounded-xl border border-gray-200 p-4 dark:border-gray-800"><h3 class="font-semibold text-gray-900 dark:text-white">{{ __('Sample rental terms') }}</h3><p class="mt-2 text-theme-xs leading-5 text-gray-600 dark:text-gray-300">{{ __('Use the equipment according to its instructions, take reasonable care and return it on the agreed date. The deposit and final contract are informational in this preview.') }}</p><label class="mt-4 flex items-start gap-2 text-theme-xs text-gray-700 dark:text-gray-300"><input type="checkbox" required class="mt-0.5 rounded border-gray-300 text-brand-600 focus:ring-brand-500"><span>{{ __('I have read the sample terms.') }}</span></label></div><div class="mt-6 flex flex-wrap gap-3"><a href="{{ route('front.reserve', ['equipment' => $item->id]) }}" class="inline-flex min-h-11 items-center rounded-lg border border-gray-300 px-4 text-theme-xs font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-200">{{ __('Change dates') }}</a><form method="GET" action="{{ route('front.payment', ['equipment' => $item->id]) }}"><input type="hidden" name="start" value="{{ $startDate }}"><input type="hidden" name="end" value="{{ $endDate }}"><button class="button-base button-primary min-h-11 px-4 text-theme-xs">{{ __('Confirm and continue to payment') }}</button></form></div></article>
                <aside class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-900 dark:text-white">{{ __('Price summary') }}</h3><dl class="mt-5 space-y-3 text-theme-xs"><div class="flex justify-between text-gray-600 dark:text-gray-300"><dt><span x-text="days"></span> × {{ number_format($item->price_per_day, 2) }} TND</dt><dd><span x-text="subtotal.toFixed(2)"></span> TND</dd></div><div class="flex justify-between text-gray-600 dark:text-gray-300"><dt>{{ __('Tax · 19%') }}</dt><dd><span x-text="tax.toFixed(2)"></span> TND</dd></div><div class="flex justify-between border-t border-gray-100 pt-3 font-semibold text-gray-900 dark:border-gray-800 dark:text-white"><dt>{{ __('Total') }}</dt><dd><span x-text="total.toFixed(2)"></span> TND</dd></div></dl></aside>
            </section>
        @elseif ($slug === 'payment')
            <form method="GET" action="{{ route('front.confirmed', ['equipment' => $item->id]) }}" x-data="{ method: 'CARD', fail: false }" class="grid items-start gap-6 lg:grid-cols-[1fr_21rem]">
                <input type="hidden" name="start" value="{{ $startDate }}"><input type="hidden" name="end" value="{{ $endDate }}">
                <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:p-7"><h2 class="text-lg font-semibold text-gray-900 dark:text-white">{{ __('Choose a payment method') }}</h2><p class="mt-1 text-theme-xs text-gray-500 dark:text-gray-400">{{ __('No real payment details are collected in this demo.') }}</p><fieldset class="mt-6 space-y-3"><legend class="sr-only">{{ __('Payment method') }}</legend>@foreach (['CARD' => __('Card'), 'BANK_TRANSFER' => __('Bank transfer'), 'CASH' => __('Cash on pickup')] as $value => $label)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-gray-200 p-4 transition-colors has-[:checked]:border-brand-500 has-[:checked]:bg-brand-50 dark:border-gray-800 dark:has-[:checked]:border-brand-500 dark:has-[:checked]:bg-brand-500/10"><input type="radio" name="method" value="{{ $value }}" x-model="method" class="border-gray-300 text-brand-600 focus:ring-brand-500"><span class="flex-1 text-theme-sm font-medium text-gray-900 dark:text-white">{{ $label }}</span><span class="text-theme-xs text-gray-500">{{ $value }}</span></label>@endforeach</fieldset><div x-show="fail" x-cloak role="alert" class="mt-5 rounded-xl border border-error-200 bg-error-50 px-4 py-3 text-theme-xs text-error-800 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-200">{{ __('Sample payment failed. No charge was made; try again or choose another method.') }}</div><div class="mt-6 flex flex-wrap gap-3"><button type="submit" class="button-base button-primary min-h-11 flex-1 px-4 text-theme-sm">{{ __('Simulate successful payment') }}</button><button type="button" @click="fail = true" class="min-h-11 rounded-lg border border-gray-300 px-4 text-theme-xs font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-200">{{ __('Simulate failure') }}</button></div></section>
                <aside class="rounded-2xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><h3 class="font-semibold text-gray-900 dark:text-white">{{ __('Order summary') }}</h3><p class="mt-3 text-theme-xs text-gray-600 dark:text-gray-300">{{ $item->name }} · {{ $startDate ?: __('Dates not selected') }} – {{ $endDate }}</p><p class="mt-5 border-t border-gray-100 pt-4 text-theme-xs text-gray-500 dark:border-gray-800">{{ __('Estimated total') }}</p><p class="mt-1 text-2xl font-semibold text-gray-900 dark:text-white">{{ $startDate && $endDate ? number_format(((strtotime($endDate) - strtotime($startDate)) / 86400 + 1) * $item->price_per_day * 1.19, 2) : '0.00' }} TND</p></aside>
            </form>
        @elseif ($slug === 'confirmed')
            <section class="mx-auto max-w-2xl rounded-3xl border border-success-200 bg-white p-7 text-center shadow-theme-md dark:border-success-500/30 dark:bg-white/[0.03] sm:p-10"><span class="mx-auto flex size-16 items-center justify-center rounded-full bg-success-50 text-3xl text-success-700 dark:bg-success-500/15 dark:text-success-300" aria-hidden="true">✓</span><p class="mt-5 text-theme-xs font-semibold uppercase tracking-[0.16em] text-success-700 dark:text-success-300">{{ __('Payment simulation successful') }}</p><h2 class="mt-2 text-2xl font-semibold text-gray-900 dark:text-white">{{ __('Your reservation is confirmed!') }}</h2><p class="mt-3 text-theme-sm text-gray-600 dark:text-gray-300">{{ __('Reference') }} <strong class="text-gray-900 dark:text-white">RES-1042</strong> · {{ $item->name }}</p><p class="mt-2 text-theme-xs text-gray-500">{{ __('This confirmation is an example and was not saved to an account.') }}</p><div class="mt-7 flex flex-wrap justify-center gap-3"><a href="{{ route('front.invoice', ['equipment' => $item->id]) }}" class="button-base button-primary min-h-11 px-5 text-theme-sm">{{ __('View invoice') }}</a><a href="{{ route('front.my-dashboard') }}" class="inline-flex min-h-11 items-center rounded-lg border border-gray-300 px-5 text-theme-xs font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-200">{{ __('My dashboard') }}</a></div></section>
        @else
            <section class="mx-auto max-w-3xl rounded-2xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:p-9">
                <div class="flex flex-wrap items-start justify-between gap-4 border-b border-gray-100 pb-5 dark:border-gray-800"><div><p class="text-theme-xs font-semibold uppercase tracking-wider text-brand-700 dark:text-brand-300">{{ __('SolarShare invoice') }}</p><h2 class="mt-2 text-xl font-semibold text-gray-900 dark:text-white">INV-2026-0142</h2><p class="mt-1 text-theme-xs text-gray-500">{{ __('Reservation RES-1042 · Issued 3 Oct 2026') }}</p></div><button type="button" onclick="window.print()" class="min-h-10 rounded-lg border border-gray-300 px-4 text-theme-xs font-semibold dark:border-gray-700">{{ __('Print / save as PDF') }}</button></div>
                <div class="py-6"><p class="font-semibold text-gray-900 dark:text-white">{{ $item->name }}</p><p class="mt-1 text-theme-xs text-gray-500">{{ __('Owner') }}: {{ $item->owner }} · {{ __('Rental dates') }}: {{ $startDate ?: '9 Oct 2026' }} – {{ $endDate ?: '11 Oct 2026' }}</p></div>
                <div class="overflow-x-auto"><table class="w-full min-w-[440px] text-start text-theme-sm"><thead class="border-b border-gray-200 text-theme-xs text-gray-500 dark:border-gray-800"><tr><th class="py-3 text-start font-medium">{{ __('Description') }}</th><th class="py-3 text-end font-medium">{{ __('Amount') }}</th></tr></thead><tbody><tr><td class="py-4 text-gray-700 dark:text-gray-300">{{ __('Equipment rental') }} · {{ $item->name }}</td><td class="py-4 text-end text-gray-900 dark:text-white">{{ number_format($item->price_per_day * 3, 2) }} TND</td></tr><tr><td class="py-3 text-gray-600 dark:text-gray-400">{{ __('Tax · 19%') }}</td><td class="py-3 text-end text-gray-800 dark:text-gray-200">{{ number_format($item->price_per_day * 3 * .19, 2) }} TND</td></tr></tbody><tfoot class="border-t border-gray-200 font-semibold text-gray-900 dark:border-gray-800 dark:text-white"><tr><td class="pt-4">{{ __('Total paid') }}</td><td class="pt-4 text-end">{{ number_format($item->price_per_day * 3 * 1.19, 2) }} TND</td></tr></tfoot></table></div>
                <p class="mt-6 rounded-xl bg-warning-50 p-4 text-theme-xs text-warning-900 dark:bg-warning-500/10 dark:text-warning-200">{{ __('Sample invoice only. This is not a tax document or payment record.') }}</p>
            </section>
        @endif
    </main>
@endsection
