@extends('layouts.front')

@section('content')
    <section class="bg-gray-950 text-white"><div class="mx-auto max-w-7xl px-4 py-9 sm:px-8 lg:px-10"><p class="text-theme-xs font-semibold uppercase tracking-[0.2em] text-warning-300">{{ $owner ? __('Owner workspace') : __('Renter workspace') }}</p><h1 class="mt-2 text-title-sm font-semibold sm:text-title-md">{{ $title }}</h1></div></section>
    @if ($owner) @include('pages.front.partials.owner-nav') @else @include('pages.front.partials.buyer-nav') @endif
    <main class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-8 lg:px-10">
        @if (session('status'))<div role="status" class="rounded-xl border border-success-200 bg-success-50 p-4 text-theme-sm text-success-800 dark:border-success-500/30 dark:bg-success-500/10 dark:text-success-200">{{ session('status') }}</div>@endif
        @if ($errors->any())<div role="alert" class="rounded-xl border border-error-200 bg-error-50 p-4 text-theme-sm text-error-800 dark:border-error-500/30 dark:bg-error-500/10 dark:text-error-200">{{ $errors->first() }}</div>@endif

        @if ($slug === 'my-reservations')
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><table class="w-full min-w-[760px] text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Reference') }}</th><th class="p-4 text-start">{{ __('Equipment') }}</th><th class="p-4 text-start">{{ $owner ? __('Renter') : __('Owner') }}</th><th class="p-4 text-start">{{ __('Rental dates') }}</th><th class="p-4 text-start">{{ __('Total') }}</th><th class="p-4 text-start">{{ __('Status') }}</th><th class="p-4 text-start">{{ __('Actions') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
                @forelse ($reservations as $reservation)
                    <tr class="text-gray-700 dark:text-gray-300"><td class="p-4 font-semibold"><a href="{{ $owner ? route('front.my-reservation-detail', $reservation->reference) : route('front.buyer-reservation-detail', $reservation->reference) }}" class="text-brand-700 hover:underline dark:text-brand-300">{{ $reservation->reference }}</a></td><td class="p-4">{{ $reservation->equipment?->name ?? __('Deleted equipment') }}</td><td class="p-4">{{ $owner ? $reservation->user?->name : $reservation->equipment?->owner?->name }}</td><td class="p-4">{{ $reservation->start_date->format('M j, Y') }} – {{ $reservation->end_date->format('M j, Y') }}</td><td class="p-4">{{ number_format((float) $reservation->total_amount * 1.19, 2) }} TND</td><td class="p-4">{{ __(ucfirst($reservation->status)) }}</td><td class="p-4">
                        @if ($owner && $reservation->status === 'pending')<form method="POST" action="{{ route('owner.reservations.decision', $reservation) }}" class="flex gap-2">@csrf<input type="hidden" name="decision" value="approve"><button class="rounded-lg bg-success-50 px-3 py-2 text-theme-xs font-semibold text-success-700 dark:bg-success-500/15 dark:text-success-300">{{ __('Approve') }}</button></form><form method="POST" action="{{ route('owner.reservations.decision', $reservation) }}" class="mt-1">@csrf<input type="hidden" name="decision" value="reject"><button class="rounded-lg bg-error-50 px-3 py-2 text-theme-xs font-semibold text-error-700 dark:bg-error-500/15 dark:text-error-300">{{ __('Decline') }}</button></form>
                        @elseif (! $owner && $reservation->status === 'confirmed' && ! $reservation->payments->contains('status', 'paid'))<a class="font-semibold text-brand-700 dark:text-brand-300" href="{{ route('front.booking-summary', ['equipment' => $reservation->equipment_id, 'reservation' => $reservation->id]) }}">{{ __('Pay / continue') }}</a>
                        @elseif (! $owner)<a class="font-semibold text-brand-700 dark:text-brand-300" href="{{ route('front.booking-summary', ['equipment' => $reservation->equipment_id, 'reservation' => $reservation->id]) }}">{{ __('Details') }}</a>@endif
                    </td></tr>
                @empty<tr><td colspan="7" class="p-8 text-center text-gray-500">{{ __('No reservations yet.') }} <a href="{{ route('front.catalog') }}" class="font-semibold text-brand-700 dark:text-brand-300">{{ __('Browse equipment') }}</a></td></tr>@endforelse
            </tbody></table></section>
        @elseif ($slug === 'my-rentals')
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="p-4 border-b border-gray-200 dark:border-gray-800"><p class="text-theme-xs font-semibold text-gray-500 dark:text-gray-400">{{ __('Live account data.') }}</p></div><table class="w-full min-w-[680px] text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Rental reference') }}</th><th class="p-4 text-start">{{ __('Equipment') }}</th><th class="p-4 text-start">{{ __('Renter') }}</th><th class="p-4 text-start">{{ __('Dates') }}</th><th class="p-4 text-start">{{ __('Total') }}</th><th class="p-4 text-start">{{ __('Status') }}</th><th class="p-4 text-start">{{ __('Contract') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
                @forelse ($rentals as $rental)<tr class="text-gray-700 dark:text-gray-300"><td class="p-4 font-semibold"><a href="{{ $owner ? route('front.my-rental-detail', $rental->reference) : route('front.buyer-rental-detail', $rental->reference) }}" class="text-brand-700 hover:underline dark:text-brand-300">{{ $rental->reference }}</a></td><td class="p-4">{{ $rental->equipment?->name ?? __('Deleted equipment') }}</td><td class="p-4">{{ $rental->user?->name }}</td><td class="p-4">{{ $rental->start_date->format('M j, Y') }} – {{ $rental->end_date->format('M j, Y') }}</td><td class="p-4">{{ number_format((float) $rental->total_amount, 2) }} TND</td><td class="p-4">{{ __($rental->status->label()) }}</td><td class="p-4">{{ $rental->contract?->contract_number ?? __('Pending') }}</td></tr>
                @empty<tr><td colspan="7" class="p-8 text-center text-gray-500">{{ __('No rentals yet. A rental is created after payment is verified.') }}</td></tr>@endforelse
            </tbody></table></section>
        @elseif (in_array($slug, ['my-payments', 'my-earnings'], true))
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><table class="w-full min-w-[600px] text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Transaction') }}</th><th class="p-4 text-start">{{ __('Reservation') }}</th><th class="p-4 text-start">{{ __('Method') }}</th><th class="p-4 text-start">{{ __('Amount') }}</th><th class="p-4 text-start">{{ __('Status') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse ($payments as $payment)<tr><td class="p-4">{{ $payment->transaction_reference }}</td><td class="p-4">{{ $payment->reservation?->reference }}</td><td class="p-4">{{ __(str_replace('_', ' ', ucfirst(strtolower($payment->payment_method)))) }}</td><td class="p-4">{{ number_format((float) $payment->amount, 2) }} TND</td><td class="p-4">{{ __(ucfirst($payment->status)) }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-gray-500">{{ __('No payments yet.') }}</td></tr>@endforelse</tbody></table></section>
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><h2 class="p-4 font-semibold text-gray-900 dark:text-white">{{ __('Invoices') }}</h2><table class="w-full text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Invoice') }}</th><th class="p-4 text-start">{{ __('Reservation') }}</th><th class="p-4 text-start">{{ __('Total') }}</th><th class="p-4 text-start">{{ __('Status') }}</th></tr></thead><tbody>@forelse ($reservations->whereNotNull('invoice') as $reservation)<tr><td class="p-4">{{ $reservation->invoice->invoice_number }}</td><td class="p-4">{{ $reservation->reference }}</td><td class="p-4">{{ number_format((float) $reservation->invoice->total, 2) }} TND</td><td class="p-4">{{ __(ucfirst($reservation->invoice->status)) }}</td></tr>@empty<tr><td colspan="4" class="p-4 text-gray-500">{{ __('No invoices yet.') }}</td></tr>@endforelse</tbody></table></section>
        @elseif ($slug === 'my-contract')
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><table class="w-full text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Contract') }}</th><th class="p-4 text-start">{{ __('Rental') }}</th><th class="p-4 text-start">{{ __('Equipment') }}</th><th class="p-4 text-start">{{ __('Status') }}</th><th class="p-4 text-start">{{ __('Terms') }}</th><th class="p-4 text-start">{{ __('Action') }}</th></tr></thead><tbody>@forelse ($contracts as $contract)<tr><td class="p-4">{{ $contract->contract_number }}</td><td class="p-4">{{ $contract->rental?->reference }}</td><td class="p-4">{{ $contract->rental?->equipment?->name }}</td><td class="p-4">{{ __($contract->contract_status->label()) }}</td><td class="p-4">{{ $contract->terms }}</td><td class="p-4">@if (! $owner && $contract->contract_status->value === 'draft')<form method="POST" action="{{ route('buyer.contracts.sign', $contract) }}">@csrf<button class="rounded-lg bg-brand-50 px-3 py-2 text-theme-xs font-semibold text-brand-700 dark:bg-brand-500/15 dark:text-brand-300">{{ __('Sign contract') }}</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">{{ __('No rental contracts yet.') }}</td></tr>@endforelse</tbody></table></section>
        @else
            <section class="overflow-x-auto rounded-2xl border border-gray-200 bg-white dark:border-gray-800 dark:bg-white/[0.03]"><div class="p-4 border-b border-gray-200 dark:border-gray-800"><p class="text-theme-xs font-semibold text-gray-500 dark:text-gray-400">{{ __('Live account data.') }}</p></div><table class="w-full min-w-[650px] text-start text-theme-sm"><thead class="bg-gray-50 text-theme-xs text-gray-500 dark:bg-white/5"><tr><th class="p-4 text-start">{{ __('Rental') }}</th><th class="p-4 text-start">{{ __('Equipment') }}</th><th class="p-4 text-start">{{ __('Old end date') }}</th><th class="p-4 text-start">{{ __('Requested end date') }}</th><th class="p-4 text-start">{{ __('Extra amount') }}</th><th class="p-4 text-start">{{ __('Status') }}</th></tr></thead><tbody>@forelse ($extensions as $extension)<tr><td class="p-4">{{ $extension->rental?->reference }}</td><td class="p-4">{{ $extension->rental?->equipment?->name }}</td><td class="p-4">{{ $extension->old_end_date->format('M j, Y') }}</td><td class="p-4">{{ $extension->new_end_date->format('M j, Y') }}</td><td class="p-4">{{ number_format((float) $extension->additional_amount, 2) }} TND</td><td class="p-4">{{ __($extension->status->label()) }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-gray-500">{{ __('No extension requests yet.') }}</td></tr>@endforelse</tbody></table></section>
        @endif
    </main>
@endsection
