<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Referral code generated by a user.
 */
class ReferralCode extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'referral_codes';

    protected $fillable = [
        'user_id',
        'code',
        'type',
        'referrer_reward',
        'referee_discount',
        'max_uses',
        'uses_count',
        'expires_at',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'referrer_reward' => 'decimal:2',
            'referee_discount' => 'decimal:2',
            'expires_at' => 'datetime',
            'is_active' => 'boolean',
        ];
    }

    /** The user who owns this referral code. */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /** Referrals generated by this code. */
    public function referrals(): HasMany
    {
        return $this->hasMany(Referral::class);
    }

    /** Check if code can be used. */
    public function canBeUsed(): bool
    {
        if (! $this->is_active) {
            return false;
        }

        if ($this->expires_at && $this->expires_at < now()) {
            return false;
        }

        if ($this->max_uses && $this->uses_count >= $this->max_uses) {
            return false;
        }

        return true;
    }

    /** Increment usage count. */
    public function incrementUsage(): void
    {
        $this->increment('uses_count');
    }
}
